In [ ]:
!pip install tensorflow_text==2.12.0

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.0/6.0 MB 14.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 585.9/585.9 MB 2.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 92.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.6/5.6 MB 94.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 440.7/440.7 kB 48.7 MB/s eta 0:00:00
  Attempting uninstall: tensorflow-estimator
    Found existing installation: tensorflow-estimator 2.13.0
    Uninstalling tensorflow-estimator-2.13.0:
      Successfully uninstalled tensorflow-estimator-2.13.0
  Attempting uninstall: keras
    Found existing installation: keras 2.13.1
    Uninstalling keras-2.13.1:
      Successfully uninstalled keras-2.13.1
  Attempting uninstall: tensorboard
    Found existing installation: tensorboard 2.13.0
    Uninstalling tensorboard-2.13.0:
      Successfully uninstalled tensorboard-2.13.0
  Attempting uninstall: tensorflow
    Found existing installati

In [ ]:
# !rm -r /usr/local/lib/python3.10/dist-packages/tensorflow_text-2.13.0.dist-info

In [ ]:
import tensorflow as tf
import tensorflow_hub as hub
import tensorflow_text as text
# import tensorflow_text as text

In [ ]:
tf.__version__

'2.12.0'

In [ ]:
encoder_url = 'https://tfhub.dev/tensorflow/bert_en_uncased_L-12_H-768_A-12/4'
preprocessor_url = 'https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/3'

In [ ]:
bert_preprocess_model = hub.KerasLayer(preprocessor_url)

In [ ]:
test_text = ['one of the greatest movies', 'total waste of time', 'okay movie']

# Preprocessor model will return a python dictionary with key value pairs
text_preprocessed = bert_preprocess_model(test_text)

In [ ]:
# checking keys to look for values
text_preprocessed.keys()

dict_keys(['input_type_ids', 'input_word_ids', 'input_mask'])

In [ ]:
#  CLS token, setence words broken down into tokens, SEP token
text_preprocessed['input_type_ids']

<tf.Tensor: shape=(3, 128), dtype=int32, numpy=
array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0

In [ ]:
#  CLS token, setence words broken down into tokens, SEP token
text_preprocessed['input_word_ids']

<tf.Tensor: shape=(3, 128), dtype=int32, numpy=
array([[ 101, 2028, 1997, 1996, 4602, 5691,  102,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0],
       [ 101, 2561, 5949, 1997, 2051,  102,    0,    0,    0,    0,    0,
           0,

In [ ]:
#  CLS token, setence words broken down into tokens, SEP token
text_preprocessed['input_mask']

<tf.Tensor: shape=(3, 128), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0

In [ ]:
bert_model = hub.KerasLayer(encoder_url)

In [ ]:
bert_results = bert_model(text_preprocessed)
bert_results.keys()

dict_keys(['pooled_output', 'default', 'encoder_outputs', 'sequence_output'])

In [ ]:
bert_results['default']

<tf.Tensor: shape=(3, 768), dtype=float32, numpy=
array([[-0.86830723, -0.32470652, -0.22818841, ..., -0.10467341,
        -0.56654936,  0.8582594 ],
       [-0.82238656, -0.24882124, -0.10054431, ...,  0.0061265 ,
        -0.5424012 ,  0.80851674],
       [-0.8930248 , -0.34914902, -0.14599541, ..., -0.06188244,
        -0.60322946,  0.91051245]], dtype=float32)>

In [ ]:
# 768 sized vector embeddings for each sentence
bert_results['pooled_output']

<tf.Tensor: shape=(3, 768), dtype=float32, numpy=
array([[-0.86830723, -0.32470652, -0.22818841, ..., -0.10467341,
        -0.56654936,  0.8582594 ],
       [-0.82238656, -0.24882124, -0.10054431, ...,  0.0061265 ,
        -0.5424012 ,  0.80851674],
       [-0.8930248 , -0.34914902, -0.14599541, ..., -0.06188244,
        -0.60322946,  0.91051245]], dtype=float32)>

In [ ]:
# 3 specifies the number of sentences
# each sentence is converted into 128-word embeddings with (the number of words of sentence + '0,0,0' padding = 128)
# each of the 128 words have their own feature vectors with size of 768
# this model has 12 encoders therefore we have a range of encoder outputs from 0 to 11
bert_results['encoder_outputs'][11]

<tf.Tensor: shape=(3, 128, 768), dtype=float32, numpy=
array([[[-2.27250442e-01, -4.06116210e-02, -9.50522646e-02, ...,
         -3.14662278e-01,  3.23745131e-01,  9.79202613e-02],
        [-3.08352917e-01, -9.09445286e-02, -6.80602491e-02, ...,
          2.20148847e-01,  6.85336947e-01,  4.15302455e-01],
        [-9.86639917e-01, -6.53324604e-01,  2.21068710e-02, ...,
         -1.19405590e-01,  1.05191875e+00,  6.67646945e-01],
        ...,
        [-1.78530619e-01, -3.18776220e-01,  5.66157997e-01, ...,
          2.81141043e-01,  2.84301251e-01,  2.05741182e-01],
        [-2.89585352e-01, -3.81576478e-01,  4.50957239e-01, ...,
          3.01113278e-01,  3.06473225e-01,  6.85149357e-02],
        [-2.40676194e-01, -1.88033611e-01,  5.76360703e-01, ...,
          2.95108438e-01,  2.14468479e-01,  2.45811433e-01]],

       [[-2.87989587e-01,  2.79474258e-01, -1.79887310e-01, ...,
         -1.42951846e-01,  3.39768112e-01,  9.83382203e-03],
        [ 5.31800568e-01,  4.57390279e-01,  5.34

In [ ]:
# 3 specifies the number of sentences
# each sentence is converted into 128-word embeddings with (the number of words of sentence + '0,0,0' padding = 128)
# each of the 128 words have their own feature vectors with size of 768
bert_results['sequence_output'][2]

<tf.Tensor: shape=(128, 768), dtype=float32, numpy=
array([[ 1.6747039e-02, -1.0870165e-01,  1.1039867e-01, ...,
        -2.8365856e-01,  3.3357289e-01,  1.3198563e-01],
       [ 5.4565227e-01, -1.0356752e+00,  1.0860301e+00, ...,
        -1.5736836e-01,  5.9593618e-01, -4.8031203e-02],
       [ 2.1489623e-01, -9.0219444e-01,  1.0467538e-01, ...,
         7.1036085e-02,  7.7868944e-01, -2.2949143e-01],
       ...,
       [-1.8113758e-02, -3.2095394e-01,  8.4064353e-01, ...,
         1.0471156e-01,  1.9338587e-01,  2.2140853e-02],
       [-1.9719200e-01, -7.6457149e-01,  3.8593405e-01, ...,
         2.7539062e-01,  2.2855628e-01, -2.3103026e-01],
       [ 9.7506121e-04, -4.0762791e-01,  7.5694519e-01, ...,
         1.3568760e-01,  2.1841043e-01, -8.0700099e-02]], dtype=float32)>