In [ ]:
import numpy as np
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Embedding

In [ ]:
reviews = ['delicious food',
           'exquisite food',
           'scrumptious food',
           'amazing restaurant',
           'too good',
           'absolutely loving it',
           'will go again',
           'disgusting place',
           'horrible food',
           'shitty service',
           'never gonna go there',
           'bad quality ingredients',
           'waste of money',
           'needs a lot of improvement']

sentiments = np.array([1,1,1,1,1,1,1,0,0,0,0,0,0,0])

In [ ]:
# will create a vector with a hot_encoded value for each word where 50 is the range.
one_hot('delicious food',50)

In [ ]:
# creating encoded vectors for all words
vocab_size = 50
encoded_reviews = [one_hot(i , vocab_size) for i in reviews]
print(encoded_reviews)


[[15, 7], [30, 7], [10, 7], [41, 28], [28, 43], [49, 34, 3], [39, 37, 23], [27, 7], [47, 7], [31, 23], [15, 6, 37, 33], [5, 41, 37], [39, 13, 15], [36, 42, 7, 13, 18]]


# **Running a for loop on array reviews and printing elements**
# **Code:**

    for i in reviews:
      print(i)

# **Output:**
delicious food

exquisite food

scrumptious food

amazing restaurant

too good

absolutely loving it

will go again

disgusting place

horrible food

shitty service

never gonna go there

bad quality ingredients

waste of money

needs a lot of improvement


In [ ]:
# padding all vectors to the length of vector with max_size. We do this so all vectors become of the same length.
max_length = 5
padded_reviews = pad_sequences(encoded_reviews, maxlen=max_length, padding = 'post')
padded_reviews

array([[15,  7,  0,  0,  0],
       [30,  7,  0,  0,  0],
       [10,  7,  0,  0,  0],
       [41, 28,  0,  0,  0],
       [28, 43,  0,  0,  0],
       [49, 34,  3,  0,  0],
       [39, 37, 23,  0,  0],
       [27,  7,  0,  0,  0],
       [47,  7,  0,  0,  0],
       [31, 23,  0,  0,  0],
       [15,  6, 37, 33,  0],
       [ 5, 41, 37,  0,  0],
       [39, 13, 15,  0,  0],
       [36, 42,  7, 13, 18]], dtype=int32)

In [ ]:
feature_vector_size = 5
model = Sequential()
model.add(Embedding(vocab_size, feature_vector_size, input_length = max_length, name = 'embedding' ))
model.add(Flatten())
model.add(Dense(1, activation="sigmoid"))

In [ ]:
X = padded_reviews
Y = sentiments

In [ ]:
model.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 5, 5)              250       
                                                                 
 flatten (Flatten)           (None, 25)                0         
                                                                 
 dense (Dense)               (None, 1)                 26        
                                                                 
Total params: 276
Trainable params: 276
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model.fit(X,Y,epochs=50)

Epoch 1/50
1/1 [==============================] - 0s 12ms/step - loss: 0.5274 - accuracy: 0.8571
Epoch 2/50
1/1 [==============================] - 0s 11ms/step - loss: 0.5255 - accuracy: 0.8571
Epoch 3/50
1/1 [==============================] - 0s 10ms/step - loss: 0.5236 - accuracy: 0.8571
Epoch 4/50
1/1 [==============================] - 0s 10ms/step - loss: 0.5217 - accuracy: 0.8571
Epoch 5/50
1/1 [==============================] - 0s 10ms/step - loss: 0.5198 - accuracy: 0.8571
Epoch 6/50
1/1 [==============================] - 0s 10ms/step - loss: 0.5179 - accuracy: 0.8571
Epoch 7/50
1/1 [==============================] - 0s 10ms/step - loss: 0.5159 - accuracy: 0.8571
Epoch 8/50
1/1 [==============================] - 0s 9ms/step - loss: 0.5140 - accuracy: 0.8571
Epoch 9/50
1/1 [==============================] - 0s 9ms/step - loss: 0.5121 - accuracy: 0.8571
Epoch 10/50
1/1 [==============================] - 0s 12ms/step - loss: 0.5102 - accuracy: 0.8571
Epoch 11/50
1/1 [==============

In [ ]:
loss, accuracy = model.evaluate(X,Y)

1/1 [==============================] - 0s 26ms/step - loss: 0.4317 - accuracy: 1.0000


In [ ]:
weights = model.get_layer('embedding').get_weights()[0]

In [ ]:
weights[47]

array([-0.19431162,  0.12276457, -0.17403208,  0.16916366,  0.12196428],
      dtype=float32)

In [ ]:
weights[5]

array([-0.10960162,  0.14833297, -0.17183144,  0.10908185,  0.19557904],
      dtype=float32)