In [ ]:
from google.colab import drive

drive.mount('/content/gdrive')

Mounted at /content/gdrive


In [ ]:
import tensorflow as tf
from tensorflow import keras
import matplotlib.pyplot as plt
import numpy as np

In [ ]:
tf.config.experimental.list_logical_devices()

[LogicalDevice(name='/device:CPU:0', device_type='CPU'),
 LogicalDevice(name='/device:GPU:0', device_type='GPU')]

In [ ]:
tf.test.is_built_with_cuda()

True

In [ ]:
print(tf.__version__)

2.12.0


In [ ]:
(X_train, y_train), (X_test,y_test) = tf.keras.datasets.cifar10.load_data()

In [ ]:
X_test.shape

(10000, 32, 32, 3)

In [ ]:
X_train.shape

(50000, 32, 32, 3)

In [ ]:
X_train[0][0][0]

array([59, 62, 63], dtype=uint8)

In [ ]:
classes = ["airplane","automobile","bird","cat","deer","dog","frog","horse","ship","truck"]

In [ ]:
y_train[809][0]

3

In [ ]:
classes[y_train[809][0]]

'cat'

In [ ]:
X_train_scaled = X_train/255
X_test_scaled = X_test/255

In [ ]:
X_test_scaled[0][0]

array([[0.61960784, 0.43921569, 0.19215686],
       [0.62352941, 0.43529412, 0.18431373],
       [0.64705882, 0.45490196, 0.2       ],
       [0.65098039, 0.4627451 , 0.20784314],
       [0.62745098, 0.43921569, 0.18039216],
       [0.61176471, 0.42745098, 0.16078431],
       [0.63529412, 0.45098039, 0.18431373],
       [0.62352941, 0.44313725, 0.17647059],
       [0.61960784, 0.43529412, 0.17254902],
       [0.62352941, 0.44313725, 0.16078431],
       [0.63137255, 0.45490196, 0.16078431],
       [0.62745098, 0.43529412, 0.20392157],
       [0.63137255, 0.43529412, 0.19215686],
       [0.65098039, 0.45882353, 0.16078431],
       [0.6627451 , 0.45882353, 0.17647059],
       [0.66666667, 0.46666667, 0.17254902],
       [0.65490196, 0.45882353, 0.15686275],
       [0.63529412, 0.44313725, 0.14901961],
       [0.62745098, 0.43529412, 0.15294118],
       [0.62745098, 0.43921569, 0.16862745],
       [0.61176471, 0.42745098, 0.17254902],
       [0.58431373, 0.41960784, 0.17647059],
       [0.

In [ ]:
# for this classification problem, we do one hot encoding on y-train and y_test arrays

y_train_categorical = tf.keras.utils.to_categorical(y_train, num_classes=10, dtype='float32')
y_test_categorical = tf.keras.utils.to_categorical(y_test, num_classes=10, dtype='float32')


In [ ]:
y_train_categorical[0]

array([0., 0., 0., 0., 0., 0., 1., 0., 0., 0.], dtype=float32)

In [ ]:
model = keras.Sequential([
    # for neural netwrok we need to flatten the 2-d array into a 1-d array
    keras.layers.Flatten(input_shape=(32,32,3)),

    #hidden layers
    keras.layers.Dense(3000, activation='relu'),
    keras.layers.Dense(1000, activation='relu'),

    # output layer with 10 neurons as our dataset has 10 classes
    keras.layers.Dense(10, activation = 'sigmoid')

])

# using 'categorical_crossentropy' loss function because our label data is one hot encoded
# if our label data was a descrete value, we would use 'sparse_categorical_crossentropy'
# using SGD as optimizer because dataset is of large size

model.compile(optimizer='SGD',
loss='categorical_crossentropy',
metrics=['accuracy'])

model.fit(X_train_scaled, y_train_categorical, epochs=50 )

Epoch 1/50
1563/1563 [==============================] - 11s 6ms/step - loss: 1.8080 - accuracy: 0.3544
Epoch 2/50
1563/1563 [==============================] - 10s 7ms/step - loss: 1.6210 - accuracy: 0.4263
Epoch 3/50
1563/1563 [==============================] - 11s 7ms/step - loss: 1.5430 - accuracy: 0.4535
Epoch 4/50
1563/1563 [==============================] - 10s 6ms/step - loss: 1.4806 - accuracy: 0.4799
Epoch 5/50
1563/1563 [==============================] - 10s 7ms/step - loss: 1.4311 - accuracy: 0.4966
Epoch 6/50
1563/1563 [==============================] - 11s 7ms/step - loss: 1.3895 - accuracy: 0.5111
Epoch 7/50
1563/1563 [==============================] - 10s 6ms/step - loss: 1.3503 - accuracy: 0.5253
Epoch 8/50
1563/1563 [==============================] - 11s 7ms/step - loss: 1.3153 - accuracy: 0.5390
Epoch 9/50
1563/1563 [==============================] - 11s 7ms/step - loss: 1.2815 - accuracy: 0.5502
Epoch 10/50
1563/1563 [==============================] - 10s 6ms/step - l

In [ ]:
classes[y_test[0][0]]

'cat'

In [ ]:
classes[np.argmax(model.predict(X_test_scaled)[0])]

313/313 [==============================] - 1s 2ms/step


'cat'

In [ ]:
def getModel():
  model = keras.Sequential([
    # for neural netwrok we need to flatten the 2-d array into a 1-d array
    keras.layers.Flatten(input_shape=(32,32,3)),

    #hidden layers
    keras.layers.Dense(3000, activation='relu'),
    keras.layers.Dense(1000, activation='relu'),

    # output layer with 10 neurons as our dataset has 10 classes
    keras.layers.Dense(10, activation = 'sigmoid')

  ])

  # using 'categorical_crossentropy' loss function because our label data is one hot encoded
  # if our label data was a descrete value, we would use 'sparse_categorical_crossentropy'
  # using SGD as optimizer because dataset is of large size

  model.compile(optimizer='SGD',
  loss='categorical_crossentropy',
  metrics=['accuracy'])

  return model



In [ ]:
%%timeit -n1 -r1
with tf.device('/CPU:0'):
  cpu_model = getModel()
  cpu_model.fit(X_train_scaled, y_train_categorical, epochs=1)


1563/1563 [==============================] - 149s 95ms/step - loss: 1.8099 - accuracy: 0.3570
3min 25s ± 0 ns per loop (mean ± std. dev. of 1 run, 1 loop each)


In [ ]:
%%timeit -n1 -r1
with tf.device('/GPU:0'):
  cpu_model = getModel()
  cpu_model.fit(X_train_scaled, y_train_categorical, epochs=1)

1563/1563 [==============================] - 10s 6ms/step - loss: 1.8121 - accuracy: 0.3552
11.3 s ± 0 ns per loop (mean ± std. dev. of 1 run, 1 loop each)
